### ISSUE TITLE
Do you remember me Dung ?

### ISSUE THREAD

**Issue by lovedota** [akirasosa/react-chat#1]
Hi @akirasosa I heard that you sent me some message before i left, but i didn't receive it because after leaving company employee had to delete all accounts/chatwork.

If you want to hear from me some problems about team, feel free to contact me
skype: lovedota21
gmail: lovedota21@gmail.com

Thanks for all goods thing.

**Comment by akirasosa** [comment]
Hi Dung san!

Sorry, I didn't notice your message. I will send you a message on Skype.
